# Generated by Django 4.2.2 on 2023-12-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
